version: '3.8'
services:
  frontend:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./.docker/next/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    networks:
      - appnetwork
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge
volumes:
  db:
